import type { PhaseMeta } from "@/lib/curriculum/types";

export const PHASES: PhaseMeta[] = [
  {
    id: "phase-01",
    slug: "computing-foundations",
    order: 1,
    track: "foundations",
    title: "Computing Foundations",
    tagline: "What actually happens beneath software",
    description:
      "Representation, architecture, and the mathematical tools this path actually uses.",
    status: "available",
    estimatedHours: 16,
    skills: ["cs.representation", "cs.architecture", "cs.math"],
    modules: [
      { id: "cf-rep", slug: "representation", title: "Computer representation", description: "Bits through instructions.", lessonSlugs: ["representation"] },
      { id: "cf-arch", slug: "architecture", title: "Computer architecture", description: "CPU, memory hierarchy, GPU contrast.", lessonSlugs: [] },
      { id: "cf-math", slug: "math", title: "Mathematical foundations", description: "Logic, probability, vectors.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-02",
    slug: "programming",
    order: 2,
    track: "foundations",
    title: "Programming + Software Engineering",
    tagline: "Python, Go, Bash — used for real work",
    description:
      "Fluency where it matters: automation, APIs, testing, Git, and maintainable systems code.",
    status: "catalog",
    estimatedHours: 40,
    skills: ["prog.python", "prog.go", "prog.bash", "prog.git"],
    modules: [
      { id: "pr-py", slug: "python", title: "Python", description: "Automation, APIs, data, AI.", lessonSlugs: [] },
      { id: "pr-go", slug: "go", title: "Go", description: "Platform tooling.", lessonSlugs: [] },
      { id: "pr-se", slug: "engineering", title: "Software engineering practice", description: "Testing, Git, review.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-03",
    slug: "dsa",
    order: 3,
    track: "foundations",
    title: "Data Structures + Algorithms",
    tagline: "Structures that infrastructure uses",
    description:
      "Queues become job systems. Heaps become schedulers. Graphs become dependency graphs.",
    status: "catalog",
    estimatedHours: 24,
    skills: ["dsa.core", "dsa.complexity"],
    modules: [
      { id: "dsa-core", slug: "structures", title: "Core structures", description: "Arrays through graphs.", lessonSlugs: [] },
      { id: "dsa-infra", slug: "infrastructure", title: "Algorithms in infrastructure", description: "Caching, scheduling, hashing.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-04",
    slug: "linux-os",
    order: 4,
    track: "foundations",
    title: "Linux + Operating Systems",
    tagline: "The machine you will spend your career on",
    description:
      "Processes, memory, kernel isolation, filesystems, and the tools used to investigate a failing host.",
    status: "available",
    estimatedHours: 36,
    skills: ["linux.cli", "linux.processes", "linux.memory", "linux.kernel"],
    modules: [
      {
        id: "lx-fund",
        slug: "fundamentals",
        title: "Linux fundamentals",
        description: "Filesystem, permissions, shell composition.",
        lessonSlugs: [],
      },
      {
        id: "lx-proc",
        slug: "processes",
        title: "Processes",
        description: "PID, state, signals, systemd.",
        lessonSlugs: ["processes"],
      },
      {
        id: "lx-mem",
        slug: "memory",
        title: "Memory",
        description: "Virtual memory and OOM.",
        lessonSlugs: [],
      },
      {
        id: "lx-kernel",
        slug: "kernel",
        title: "Kernel concepts",
        description: "Syscalls, namespaces, cgroups.",
        lessonSlugs: [],
      },
    ],
  },
  {
    id: "phase-05",
    slug: "networking",
    order: 5,
    track: "foundations",
    title: "Networking + Internet Systems",
    tagline: "Packets, names, and trust",
    description: "TCP/IP, DNS, TLS, load balancers, and the tools that prove where a request died.",
    status: "available",
    estimatedHours: 32,
    skills: ["net.tcpip", "net.dns", "net.http"],
    modules: [
      { id: "net-core", slug: "foundations", title: "Networking foundations", description: "Addressing, routing, transport.", lessonSlugs: [] },
      { id: "net-app", slug: "application", title: "Application layer", description: "DNS, HTTP, TLS.", lessonSlugs: ["dns"] },
    ],
  },
  {
    id: "phase-06",
    slug: "databases",
    order: 6,
    track: "foundations",
    title: "Databases + Data Systems",
    tagline: "State that must survive",
    description: "PostgreSQL, transactions, caches, object storage, and queues.",
    status: "catalog",
    estimatedHours: 28,
    skills: ["db.sql"],
    modules: [
      { id: "db-rel", slug: "relational", title: "Relational systems", description: "SQL, ACID, pooling.", lessonSlugs: [] },
      { id: "db-aux", slug: "adjacent", title: "Caches and streams", description: "Redis, S3, queues.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-07",
    slug: "aws",
    order: 7,
    track: "production",
    title: "Cloud Engineering / AWS",
    tagline: "Someone else's datacenter, operated with intent",
    description: "IAM, VPC, compute, storage, and architecture tradeoffs — concepts before product memorization.",
    status: "catalog",
    estimatedHours: 36,
    skills: ["aws.iam", "aws.vpc"],
    modules: [
      { id: "aws-id", slug: "identity", title: "Identity", description: "IAM and STS.", lessonSlugs: [] },
      { id: "aws-net", slug: "networking", title: "VPC", description: "Subnets, routing, security groups.", lessonSlugs: [] },
      { id: "aws-ops", slug: "operations", title: "Operations", description: "CloudWatch, KMS, cost.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-08",
    slug: "devops",
    order: 8,
    track: "production",
    title: "DevOps + Delivery Engineering",
    tagline: "Ship change without gambling production",
    description: "CI/CD, artifacts, progressive delivery, and rollback as a first-class path.",
    status: "catalog",
    estimatedHours: 24,
    skills: ["devops.cicd"],
    modules: [
      { id: "dv-ci", slug: "cicd", title: "CI/CD", description: "Pipelines and environments.", lessonSlugs: [] },
      { id: "dv-rel", slug: "release", title: "Release strategies", description: "Rolling, canary, flags.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-09",
    slug: "iac",
    order: 9,
    track: "production",
    title: "Infrastructure as Code",
    tagline: "Desired state, with a paper trail",
    description: "Terraform as the primary implementation. CloudFormation enough to recognize. Pulumi and Crossplane later.",
    status: "catalog",
    estimatedHours: 24,
    skills: ["iac.terraform"],
    modules: [
      { id: "tf-core", slug: "terraform", title: "Terraform", description: "State, modules, drift.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-10",
    slug: "containers",
    order: 10,
    track: "production",
    title: "Containers",
    tagline: "Why isolation works, not only how to docker run",
    description: "Namespaces, cgroups, images, and runtime security.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["containers.isolation"],
    modules: [
      { id: "ctr-why", slug: "isolation", title: "Isolation", description: "Kernel mechanisms.", lessonSlugs: [] },
      { id: "ctr-img", slug: "images", title: "Images", description: "Layers, OCI, Dockerfiles.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-11",
    slug: "kubernetes",
    order: 11,
    track: "production",
    title: "Kubernetes",
    tagline: "Architecture before YAML memorization",
    description: "Control plane, workloads, networking, scheduling, security, Helm, and EKS.",
    status: "available",
    estimatedHours: 48,
    skills: ["k8s.architecture", "k8s.workloads", "k8s.scheduling"],
    modules: [
      { id: "k8s-arch", slug: "architecture", title: "Architecture", description: "Control plane and nodes.", lessonSlugs: [] },
      { id: "k8s-wl", slug: "workloads", title: "Workloads", description: "Pods through Jobs.", lessonSlugs: ["workloads"] },
      { id: "k8s-ops", slug: "operations", title: "Operations", description: "Scheduling, security, EKS.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-12",
    slug: "observability-sre",
    order: 12,
    track: "production",
    title: "Observability + SRE",
    tagline: "See everything. Page rarely.",
    description: "OpenTelemetry, Prometheus, SLOs, and incident command.",
    status: "catalog",
    estimatedHours: 28,
    skills: ["obs.signals", "obs.prometheus", "sre.slo"],
    modules: [
      { id: "obs-sig", slug: "signals", title: "Signals", description: "Logs, metrics, traces.", lessonSlugs: [] },
      { id: "obs-sre", slug: "sre", title: "SRE practice", description: "SLOs and incidents.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-13",
    slug: "security",
    order: 13,
    track: "production",
    title: "Security + Software Supply Chain",
    tagline: "Defensive engineering, not theater",
    description: "Identity, TLS, secrets, signing, SBOMs, and admission policy.",
    status: "catalog",
    estimatedHours: 24,
    skills: ["sec.identity"],
    modules: [
      { id: "sec-id", slug: "identity", title: "Identity and crypto", description: "AuthN, TLS, KMS.", lessonSlugs: [] },
      { id: "sec-sc", slug: "supply-chain", title: "Supply chain", description: "Provenance and policy.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-14",
    slug: "distributed-systems",
    order: 14,
    track: "production",
    title: "Distributed Systems",
    tagline: "Correctness under partial failure",
    description: "Retries, idempotency, consistency, consensus, and event-driven design.",
    status: "catalog",
    estimatedHours: 32,
    skills: ["dist.fundamentals"],
    modules: [
      { id: "ds-fail", slug: "failure", title: "Failure and time", description: "Retries, timeouts, clocks.", lessonSlugs: [] },
      { id: "ds-data", slug: "data", title: "Data and consensus", description: "Replication, quorum, CAP.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-15",
    slug: "platform-foundations",
    order: 15,
    track: "platform",
    title: "Platform Engineering Foundations",
    tagline: "Reusable capabilities, not a ticket queue",
    description: "Platform as a product: cognitive load, self-service, and paved roads.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["plat.foundations"],
    modules: [
      { id: "pf-why", slug: "why", title: "Why platforms exist", description: "Product, not ops theater.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-16",
    slug: "developer-experience",
    order: 16,
    track: "platform",
    title: "Developer Experience + Golden Paths",
    tagline: "The Create Service button is a product",
    description: "Onboarding, templates, local-to-prod journeys, and ownership metadata.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["plat.golden-paths"],
    modules: [
      { id: "dx-path", slug: "golden-paths", title: "Golden paths", description: "Scaffolding a service.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-17",
    slug: "idp",
    order: 17,
    track: "platform",
    title: "Internal Developer Platforms",
    tagline: "Catalog, docs, and the portal as an interface",
    description: "Software catalogs, templates, and TechDocs — architecture independent of Backstage.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["plat.golden-paths"],
    modules: [
      { id: "idp-cat", slug: "catalog", title: "Catalog and portal", description: "Ownership and discovery.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-18",
    slug: "control-planes",
    order: 18,
    track: "platform",
    title: "Platform APIs + Control Planes",
    tagline: "kind: Application",
    description: "Declarative APIs, reconciliation, operators, and Crossplane.",
    status: "catalog",
    estimatedHours: 20,
    skills: ["plat.control-planes"],
    modules: [
      { id: "cp-api", slug: "apis", title: "Platform APIs", description: "Desired state to infrastructure.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-19",
    slug: "governance-finops",
    order: 19,
    track: "platform",
    title: "Multi-tenancy + Governance + FinOps",
    tagline: "Boundaries, quotas, and the bill",
    description: "Tenants, policy, showback, and capacity.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["plat.foundations"],
    modules: [
      { id: "gov-ten", slug: "tenancy", title: "Tenancy and cost", description: "Quotas and allocation.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-20",
    slug: "ml-math",
    order: 20,
    track: "ai",
    title: "Math for Machine Learning",
    tagline: "Enough math to see the systems",
    description: "Vectors, gradients, loss, and distributions — visual, not a degree.",
    status: "catalog",
    estimatedHours: 12,
    skills: ["cs.math"],
    modules: [
      { id: "mlm-core", slug: "core", title: "Core math", description: "The minimum that pays rent.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-21",
    slug: "ml-foundations",
    order: 21,
    track: "ai",
    title: "Machine Learning Foundations",
    tagline: "Training, inference, and the split between them",
    description: "Supervised learning, generalization, and the first PyTorch loops.",
    status: "catalog",
    estimatedHours: 24,
    skills: ["ml.foundations"],
    modules: [
      { id: "ml-core", slug: "core", title: "Foundations", description: "Features, splits, metrics.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-22",
    slug: "deep-learning",
    order: 22,
    track: "ai",
    title: "Deep Learning + Transformers",
    tagline: "Prefill, decode, KV cache",
    description: "Enough internals to understand serving, memory, and latency.",
    status: "catalog",
    estimatedHours: 24,
    skills: ["ml.transformers"],
    modules: [
      { id: "dl-tf", slug: "transformers", title: "Transformers", description: "Attention and inference.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-23",
    slug: "llm-apps",
    order: 23,
    track: "ai",
    title: "LLM Application Engineering",
    tagline: "Applications are not the platform",
    description: "Prompts, RAG, agents, and evals — so infrastructure has context.",
    status: "catalog",
    estimatedHours: 20,
    skills: ["llm.apps"],
    modules: [
      { id: "llm-app", slug: "apps", title: "Application systems", description: "RAG, tools, evals.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-24",
    slug: "mlops",
    order: 24,
    track: "ai",
    title: "ML Systems + MLOps",
    tagline: "Artifacts, registries, and rollback",
    description: "Pipelines, versioning, drift, and deployment of trained artifacts.",
    status: "catalog",
    estimatedHours: 20,
    skills: ["ml.foundations"],
    modules: [
      { id: "mlo-pipe", slug: "pipelines", title: "ML systems", description: "From dataset to rollback.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-25",
    slug: "gpu-computing",
    order: 25,
    track: "ai",
    title: "GPU Computing",
    tagline: "Memory bandwidth is the scarce resource",
    description: "CUDA concepts, precision, batching, and distributed parallelism.",
    status: "catalog",
    estimatedHours: 20,
    skills: ["gpu.computing"],
    modules: [
      { id: "gpu-core", slug: "architecture", title: "GPU architecture", description: "VRAM, precision, interconnects.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-26",
    slug: "k8s-gpu",
    order: 26,
    track: "ai",
    title: "Kubernetes GPU Infrastructure",
    tagline: "Device plugins, operators, and unschedulable GPUs",
    description: "NVIDIA GPU Operator, DCGM, MIG, and fleet operations.",
    status: "catalog",
    estimatedHours: 20,
    skills: ["gpu.scheduling"],
    modules: [
      { id: "kgpu", slug: "operations", title: "GPU operations", description: "Scheduling and failure modes.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-27",
    slug: "model-serving",
    order: 27,
    track: "ai",
    title: "Model Serving + vLLM",
    tagline: "Continuous batching is an operations problem",
    description: "TTFT, ITL, KV cache, concurrency, and why the gateway is not optional.",
    status: "available",
    estimatedHours: 20,
    skills: ["serve.vllm"],
    modules: [
      { id: "vllm", slug: "vllm", title: "vLLM operations", description: "Serving and failure modes.", lessonSlugs: ["vllm"] },
    ],
  },
  {
    id: "phase-28",
    slug: "kserve",
    order: 28,
    track: "ai",
    title: "KServe + AI Workload Orchestration",
    tagline: "Scale on queue depth, not only CPU",
    description: "InferenceService, canaries, KEDA, and inference-aware autoscaling.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["serve.vllm", "k8s.scheduling"],
    modules: [
      { id: "ksv", slug: "orchestration", title: "Orchestration", description: "Routing and scale signals.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-29",
    slug: "ai-observability",
    order: 29,
    track: "ai",
    title: "AI Observability + Evaluation",
    tagline: "Infrastructure green, product red",
    description: "DCGM, vLLM metrics, token cost, and quality signals on one board.",
    status: "preview",
    estimatedHours: 16,
    skills: ["ai.observability"],
    modules: [
      { id: "aiobs", slug: "dashboards", title: "Inference dashboards", description: "The signals that matter.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-30",
    slug: "ai-data-path",
    order: 30,
    track: "ai",
    title: "AI Networking + Storage + Data",
    tagline: "Models are large artifacts",
    description: "Object storage, locality, startup latency, and interconnects.",
    status: "catalog",
    estimatedHours: 12,
    skills: ["gpu.computing"],
    modules: [
      { id: "aidata", slug: "locality", title: "Data locality", description: "Artifacts vs images.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-31",
    slug: "ai-security",
    order: 31,
    track: "ai",
    title: "AI Security + Governance",
    tagline: "Approved models, enforced at the gateway",
    description: "Tenant isolation, provenance, audit, and policy.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["sec.identity", "ai.gateway"],
    modules: [
      { id: "aisec", slug: "governance", title: "Governance", description: "Access and provenance.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-32",
    slug: "ai-finops",
    order: 32,
    track: "ai",
    title: "AI FinOps + Capacity Engineering",
    tagline: "$450k/month at 31% utilization",
    description: "Idle GPUs, tokens-per-dollar, and the latency/cost frontier.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["ai.finops"],
    modules: [
      { id: "aicap", slug: "capacity", title: "Capacity", description: "Utilization and cost.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-33",
    slug: "model-gateway",
    order: 33,
    track: "ai",
    title: "Model Gateway",
    tagline: "Developer → gateway → router → model",
    description: "Auth, quotas, fallback, observability, and tenant boundaries.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["ai.gateway"],
    modules: [
      { id: "gw", slug: "gateway", title: "Gateway design", description: "The enforcement point.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-34",
    slug: "model-registry",
    order: 34,
    track: "ai",
    title: "Model + Artifact Registry",
    tagline: "What is approved to run",
    description: "Versions, evals, provenance, rollback, environments.",
    status: "catalog",
    estimatedHours: 10,
    skills: ["ai.platform"],
    modules: [
      { id: "reg", slug: "registry", title: "Registry", description: "Catalog of models.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-35",
    slug: "ai-developer-platform",
    order: 35,
    track: "ai",
    title: "AI Developer Platform",
    tagline: "Create AI Service",
    description: "The golden path for model-backed applications.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["plat.golden-paths", "ai.gateway"],
    modules: [
      { id: "aidp", slug: "dx", title: "AI DX", description: "From form to governed inference.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-36",
    slug: "self-service-ai",
    order: 36,
    track: "ai",
    title: "Self-Service AI Infrastructure",
    tagline: "kind: ModelDeployment",
    description: "Intent APIs that compile into GPU, serving, and policy.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["plat.control-planes", "serve.vllm"],
    modules: [
      { id: "ssai", slug: "intent", title: "Intent APIs", description: "Spec to infrastructure.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-37",
    slug: "multi-tenant-ai",
    order: 37,
    track: "ai",
    title: "Multi-Tenant AI Platform",
    tagline: "Shared GPUs without shared fate",
    description: "Pools, fairness, isolation, noisy neighbors, chargeback.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["ai.finops", "ai.platform"],
    modules: [
      { id: "mtai", slug: "tenancy", title: "AI tenancy", description: "Shared vs dedicated serving.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-38",
    slug: "agent-platform",
    order: 38,
    track: "ai",
    title: "Agent Platform Infrastructure",
    tagline: "Humans and agents on governed interfaces",
    description: "Identity, tool permissions, MCP, sandboxing, audit, cost.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["ai.platform", "ai.gateway"],
    modules: [
      { id: "agt", slug: "agents", title: "Agent workloads", description: "Execution boundaries.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-39",
    slug: "ai-reliability",
    order: 39,
    track: "ai",
    title: "Production AI Reliability",
    tagline: "Load-shed before you page everyone",
    description: "Inference SLOs, fallbacks, regional failure, and capacity.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["sre.slo", "serve.vllm"],
    modules: [
      { id: "airel", slug: "reliability", title: "Reliability", description: "Degradation and recovery.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-40",
    slug: "ai-architecture",
    order: 40,
    track: "ai",
    title: "AI Platform Architecture",
    tagline: "Portal to GPU fleet, with the cross-cuts named",
    description: "The reference architecture this academy exists to make operable.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["ai.platform"],
    modules: [
      { id: "aiarch", slug: "reference", title: "Reference architecture", description: "The whole map.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-41",
    slug: "staff-platform",
    order: 41,
    track: "ai",
    title: "Staff-Level Platform Engineering",
    tagline: "Tradeoffs, RFCs, and the room",
    description: "Architecture reviews, adoption, mentoring, and strategy.",
    status: "catalog",
    estimatedHours: 16,
    skills: ["ai.platform", "plat.foundations"],
    modules: [
      { id: "staff", slug: "leadership", title: "Staff practice", description: "How the work is decided.", lessonSlugs: [] },
    ],
  },
  {
    id: "phase-42",
    slug: "capstone",
    order: 42,
    track: "ai",
    title: "Final Capstone",
    tagline: "Design and operate the company's AI platform",
    description:
      "200 engineers, 12 AI teams, uncontrolled spend. Produce the architecture, the operating model, and the evidence.",
    status: "catalog",
    estimatedHours: 40,
    skills: ["ai.platform"],
    modules: [
      { id: "cap", slug: "northstar-platform", title: "Northstar AI platform", description: "The synthesis.", lessonSlugs: [] },
    ],
  },
];
