import type { Skill } from "@/lib/skills/types";

export const SKILLS: Skill[] = [
  {
    id: "cs.representation",
    title: "Data representation",
    category: "Computer Science",
    summary: "Bits, bytes, integers, floating point, and encoding.",
    prerequisites: [],
  },
  {
    id: "cs.architecture",
    title: "Computer architecture",
    category: "Computer Science",
    summary: "CPU, memory hierarchy, and instruction execution.",
    prerequisites: ["cs.representation"],
  },
  {
    id: "cs.math",
    title: "Engineering math",
    category: "Computer Science",
    summary: "Logic, probability, vectors, and the math that later ML needs.",
    prerequisites: [],
  },
  {
    id: "prog.python",
    title: "Python",
    category: "Programming",
    summary: "Automation, APIs, data, and AI service code.",
    prerequisites: [],
  },
  {
    id: "prog.go",
    title: "Go",
    category: "Programming",
    summary: "Systems and platform tooling.",
    prerequisites: [],
  },
  {
    id: "prog.bash",
    title: "Bash",
    category: "Programming",
    summary: "Shell composition for operations and automation.",
    prerequisites: [],
  },
  {
    id: "prog.git",
    title: "Git and review",
    category: "Programming",
    summary: "History, branches, pull requests, and review discipline.",
    prerequisites: [],
  },
  {
    id: "dsa.core",
    title: "Data structures",
    category: "Algorithms",
    summary: "The structures infrastructure actually uses: queues, heaps, graphs, maps.",
    prerequisites: ["prog.python"],
  },
  {
    id: "dsa.complexity",
    title: "Complexity and tradeoffs",
    category: "Algorithms",
    summary: "Time/space tradeoffs in caches, schedulers, and indexes.",
    prerequisites: ["dsa.core"],
  },
  {
    id: "linux.cli",
    title: "Linux command line",
    category: "Linux",
    summary: "Filesystem, permissions, pipes, and everyday investigation tools.",
    prerequisites: ["prog.bash"],
  },
  {
    id: "linux.processes",
    title: "Linux processes",
    category: "Linux",
    summary: "Process model, states, signals, trees, and systemd supervision.",
    prerequisites: ["linux.cli"],
  },
  {
    id: "linux.memory",
    title: "Virtual memory",
    category: "Operating Systems",
    summary: "Stack, heap, paging, and OOM behavior.",
    prerequisites: ["linux.processes", "cs.architecture"],
  },
  {
    id: "linux.kernel",
    title: "Kernel isolation",
    category: "Operating Systems",
    summary: "Syscalls, namespaces, and cgroups — why containers work.",
    prerequisites: ["linux.processes"],
  },
  {
    id: "net.tcpip",
    title: "TCP/IP",
    category: "Networking",
    summary: "Addressing, routing, sockets, and the transport layer.",
    prerequisites: ["cs.architecture"],
  },
  {
    id: "net.dns",
    title: "DNS",
    category: "Networking",
    summary: "Resolution, records, caching, and failure modes.",
    prerequisites: ["net.tcpip"],
  },
  {
    id: "net.http",
    title: "HTTP and TLS",
    category: "Networking",
    summary: "Request path, certificates, and proxies.",
    prerequisites: ["net.tcpip"],
  },
  {
    id: "db.sql",
    title: "Relational systems",
    category: "Databases",
    summary: "SQL, transactions, indexes, and connection pooling.",
    prerequisites: ["prog.python"],
  },
  {
    id: "aws.iam",
    title: "AWS identity",
    category: "AWS",
    summary: "Roles, policies, and least privilege.",
    prerequisites: [],
  },
  {
    id: "aws.vpc",
    title: "AWS networking",
    category: "AWS",
    summary: "VPC, subnets, routing, and security groups.",
    prerequisites: ["net.tcpip", "aws.iam"],
  },
  {
    id: "devops.cicd",
    title: "CI/CD",
    category: "Delivery",
    summary: "Build, test, package, and progressive delivery.",
    prerequisites: ["prog.git"],
  },
  {
    id: "iac.terraform",
    title: "Terraform",
    category: "IaC",
    summary: "Declarative infrastructure, state, and modules.",
    prerequisites: ["aws.vpc"],
  },
  {
    id: "containers.isolation",
    title: "Containers",
    category: "Containers",
    summary: "Namespaces, cgroups, images, and runtimes.",
    prerequisites: ["linux.kernel"],
  },
  {
    id: "k8s.architecture",
    title: "Kubernetes architecture",
    category: "Kubernetes",
    summary: "Control plane, kubelet, and desired-state reconciliation.",
    prerequisites: ["containers.isolation"],
  },
  {
    id: "k8s.workloads",
    title: "Kubernetes workloads",
    category: "Kubernetes",
    summary: "Pods, Deployments, and the objects that run software.",
    prerequisites: ["k8s.architecture"],
  },
  {
    id: "k8s.scheduling",
    title: "Kubernetes scheduling",
    category: "Kubernetes",
    summary: "Requests, limits, affinity, taints, and topology.",
    prerequisites: ["k8s.workloads"],
  },
  {
    id: "obs.signals",
    title: "Logs, metrics, traces",
    category: "Observability",
    summary: "The three signals and when each one lies.",
    prerequisites: [],
  },
  {
    id: "obs.prometheus",
    title: "Prometheus and OTel",
    category: "Observability",
    summary: "Instrumentation, PromQL, and vendor-neutral telemetry.",
    prerequisites: ["obs.signals"],
  },
  {
    id: "sre.slo",
    title: "SLOs and incidents",
    category: "SRE",
    summary: "Error budgets, alerting, and incident command.",
    prerequisites: ["obs.signals"],
  },
  {
    id: "sec.identity",
    title: "AuthN / AuthZ",
    category: "Security",
    summary: "Identity, least privilege, and zero-trust instincts.",
    prerequisites: ["aws.iam"],
  },
  {
    id: "dist.fundamentals",
    title: "Distributed systems",
    category: "Distributed Systems",
    summary: "Partial failure, retries, idempotency, and consensus.",
    prerequisites: ["net.tcpip", "db.sql"],
  },
  {
    id: "plat.foundations",
    title: "Platform as a product",
    category: "Platform Engineering",
    summary: "Cognitive load, paved roads, and platform interfaces.",
    prerequisites: ["k8s.workloads", "devops.cicd"],
  },
  {
    id: "plat.golden-paths",
    title: "Golden paths",
    category: "Developer Experience",
    summary: "Templates, scaffolding, and self-service journeys.",
    prerequisites: ["plat.foundations"],
  },
  {
    id: "plat.control-planes",
    title: "Control planes",
    category: "Platform Engineering",
    summary: "Declarative APIs, reconciliation, operators, Crossplane.",
    prerequisites: ["plat.foundations", "k8s.architecture"],
  },
  {
    id: "ml.foundations",
    title: "ML foundations",
    category: "Machine Learning",
    summary: "Training vs inference, overfitting, and classical pipelines.",
    prerequisites: ["cs.math", "prog.python"],
  },
  {
    id: "ml.transformers",
    title: "Transformers",
    category: "Deep Learning",
    summary: "Tokens, attention, prefill, decode, and KV cache.",
    prerequisites: ["ml.foundations"],
  },
  {
    id: "llm.apps",
    title: "LLM application systems",
    category: "LLMs",
    summary: "RAG, tools, evals — context for why platforms exist.",
    prerequisites: ["ml.transformers"],
  },
  {
    id: "gpu.computing",
    title: "GPU computing",
    category: "GPU",
    summary: "VRAM, precision, utilization, and interconnects.",
    prerequisites: ["cs.architecture"],
  },
  {
    id: "gpu.scheduling",
    title: "GPU scheduling",
    category: "GPU",
    summary: "Device plugins, GPU Operator, MIG, and sharing.",
    prerequisites: ["k8s.scheduling", "gpu.computing"],
  },
  {
    id: "serve.vllm",
    title: "Model serving / vLLM",
    category: "Model Serving",
    summary: "Continuous batching, KV cache, TTFT, and tokens/sec.",
    prerequisites: ["ml.transformers", "gpu.computing"],
  },
  {
    id: "ai.observability",
    title: "AI observability",
    category: "AI Observability",
    summary: "Inference metrics, DCGM, queue depth, and quality signals.",
    prerequisites: ["obs.prometheus", "serve.vllm"],
  },
  {
    id: "ai.finops",
    title: "AI FinOps",
    category: "AI FinOps",
    summary: "Tokens per dollar, idle GPUs, and capacity tradeoffs.",
    prerequisites: ["gpu.scheduling", "serve.vllm"],
  },
  {
    id: "ai.gateway",
    title: "Model gateway",
    category: "AI Platform",
    summary: "Auth, routing, quotas, and policy in front of models.",
    prerequisites: ["sec.identity", "serve.vllm"],
  },
  {
    id: "ai.platform",
    title: "AI platform architecture",
    category: "AI Platform Architecture",
    summary: "The full stack from portal to GPU fleet.",
    prerequisites: ["plat.control-planes", "ai.gateway", "ai.finops", "ai.observability"],
  },
];

export const SKILL_BY_ID = Object.fromEntries(SKILLS.map((s) => [s.id, s])) as Record<
  string,
  Skill
>;
